### ISSUE TITLE
Library does not represent the full PagerDuty REST api

### ISSUE THREAD

**Issue by jasonmoo-we** [PagerDuty/go-pagerduty#178]
Just digging through and seeing some methods missing.  Here's a few:

https://api-reference.pagerduty.com/#!/Incidents/put_incidents_id
https://api-reference.pagerduty.com/#!/Incidents/put_incidents_id_alerts_alert_id

Are these left out on purpose?

**Comment by jessedearing** [comment]
The client is also missing all methods related to tags as well. I'd like to use tags to signal some automation I'm using the client for.

**Comment by stmcallister** [comment]
Hello! No, any documented endpoints or fields that are not covered by the client are only because we haven't had the chance to add them. 

Although, @jasonmoo-we , you mention that updating an incident is not supported. I believe that can be handled with `pagerduty.ManageIncidents`. Is there something more you're looking for there?

**Comment by theckman** [comment]
@jasonmoo-we I wanted to see if you had a chance to see @stmcallister's question.

I think it's well-known (based on the PRs that have been in-flight) that there are some gaps we can address in terms of API coverage / compatibility. **Is there anyone who would like to enumerate all of the differences so that we can track them?**

Alternatively, we can close this issue and track each deviation on a case-by-case basis as they are discovered by consumers.

**Comment by theckman** [comment]
Considering the lack of activity on this issue I'm going to mark it closed now.

While there isn't a dedicated issue tracking it, I may end up enumerating all of the things that are missing as part of the v1.5.0 development effort. For that release one thing we're trying to fix are APIs that have never worked properly due to some design issue, that can only be fixed with a breaking change. So to do that I was going to try and audit all of what we have now, relative to the API documentation, to see if I can spot any more mismatches. It should be easy to find anything that's completely missing / unimplemented as part of that audit.

**Comment by theckman** [comment]
If you know of any problems with this library, such as a missing endpoint or broken support, please file a dedicated issue so we can track that being fixed up.
