### ISSUE TITLE
Return structured errors from functions that do HTTP requests

### ISSUE THREAD

**Issue by echlebek** [PagerDuty/go-pagerduty#222]
This is a similar issue to https://github.com/PagerDuty/go-pagerduty/issues/95, but somewhat distinct.

In `ManageEvent`, several different conditions can return an error. Depending on the type of error delivered, the caller might want to take a variety of actions. However, this is hard-to-impossible currently, since the function just returns a string.

One use case, for instance, is retrying a request if the HTTP status is 5xx, but not retrying the request if the HTTP status is 4xx. Or, truncating the request size if the service returns a 413 error, and trying again.

I'd suggest something like the following for a structured error type:
```
type ManageEventError struct {
  // StatusCode is the status code from the response
  StatusCode int

  // Body is the contents of the response body
  Body []byte

  // Header is the response header
  Header http.Header

  // Message is a human-readable error message
  Message string
}

func (e *ManageEventError) Error() string {
  return e.Message
}
```

Depending on the exact expectations of the submitter of #95, this should be enough information to satisfy their needs as well. The upside of doing this, is that the functionality can be implemented without breaking the API, and so can be done in a minor release. The caller can simply use a type assertion to check further error details.

**Comment by stmcallister** [comment]
Hello! Sorry for the delay on responding to this. I like your suggestion. Any chance you could submit a PR that implements this?

**Comment by theckman** [comment]
So I'm not confident the structure above makes sense for the error structure that the PagerDuty API commits to returning. It may make more sense to have the error type include the HTTP status code, as well as a structure aligned with what's here: https://developer.pagerduty.com/docs/rest-api-v2/errors/

I'm hitting an annoying case with this lack of error propagation, where I'm trying to enumerate all the active users who _could_ be paged for an incident against a service. Unfortunately, our schedule is hella old and contains deactivated users in old layers... unfortunately, we get a 404 error from the API when trying to get the details of these users. The Go API client makes it nearly impossible to programmatically know what's what happened, since I could only check that by doing a substring match against the error.

I might try to whip-up a PR that takes some inspiration from the above structure, but instead provides the error structure instead of the unparsed response body.

**Comment by theckman** [comment]
Actually, that looks to mostly exist here. I'd want to see whether I could provide something more than an `interface{}` for those errors:

https://github.com/PagerDuty/go-pagerduty/blob/eab6a10fcb58a8a86ab84ed9c14231e549a09228/client.go#L59-L63

**Comment by echlebek** [comment]
Hi @stmcallister and @theckman.

Sorry I didn't respond before. I think at the time, I was probably busy with the holiday season and your message got lost in the noise. But, now I'm glad I didn't respond, because Tim made a great point about using the structured data from PagerDuty's API.

I think that including the details from the expected error response as suggested makes a great deal of sense. Happy to do some code review if someone ends up writing this.

**Comment by theckman** [comment]
@echlebek thank you for that offer. I've a branch that I think should accomplish what both you and I want. Let me just add a blurb to the `README.md` about how to use the new exported error type, and maybe the package documentation as well, and then I'll get the PR up and tag you on it for 👀 .
