### ISSUE TITLE
ContactMethod field does not populate inside the NotificationRule on a User

### ISSUE THREAD

**Issue by stefprez** [PagerDuty/go-pagerduty#250]
When fetching a user, the `NotificationRules` get populated for that user, but the `ContactMethod` field on each `NotificationRule` in the `[]NotificationRules` always seems to be empty.

**Comment by theckman** [comment]
@stefprez can you give me an idea of how you're calling `GetUser`? Are you telling it to include the `notification_rules`?

**Comment by theckman** [comment]
@stefprez oh sorry, I misread your question originally. That is the expected behavior in terms of how PagerDuty documents their API, and the fact you expected it to be present might indicate a deficiency in our library. Please refer to [this API documentation page](https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1users~1%7Bid%7D/get).

You'll notice that under the schema for the response, the `notification_rules` array contains an object that has the following fields: `id`, `summary`, `type`, `self`, and `html_url` which is the same structure as the `APIObject` type in this package. It does not contain a `contact_method` field.

The PagerDuty REST API often returns references to the real object instead of returning the whole object in the response. This is to keep response sizes down.

**Comment by theckman** [comment]
I've opened that issue and will now close this one in favor of #279

**Comment by stefprez** [comment]
Excellent. Thanks for the additional context!
