### ISSUE TITLE
Help with posting incident notes via API

### ISSUE THREAD

**Issue by justolinas** [PagerDuty/go-pagerduty#336]
Went through some discussions, and couldn't find the answer, so trying my luck here :)
I'm trying to post an incident note using https://github.com/PagerDuty/go-pagerduty/blob/master/incident.go#L418
and can't get through `HTTP response failed with status code 400, message: Malformed \"From\" header (code: 1028)` error.
Here's a snippet of getting user info for APIObject, assembling the note and trying to post it (removed all error handling)

	user, err = client.GetUser(userID, options)

	note := pagerduty.IncidentNote{
		ID:      incidentID,
		User:    user.APIObject,
		Content: message,
	}

	noteResponse, err = client.CreateIncidentNoteWithContext(context.Background(), incidentID, note)

Here https://github.com/PagerDuty/go-pagerduty/blob/master/incident.go#L424 I've seen that it's using APIObject.Summary field for `From` header, which is empty after getting the user info.
Am I missing something obvious? :) Thank you!

**Comment by justolinas** [comment]
Just checked the documentation https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1incidents~1%7Bid%7D~1notes/post
It's looking for a user email. So I had to hack it like so.
`user.APIObject.Summary = user.Email`
and now it works :)
This definitely does not feel right after all.

**Comment by justolinas** [comment]
Just checked the documentation https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1incidents~1%7Bid%7D~1notes/post
It's looking for a user email. So I had to hack it like so.
`user.APIObject.Summary = user.Email`
and now it works :) tho does not feel right.

**Comment by theckman** [comment]
It looks like this was added a long time ago in this PR: https://github.com/PagerDuty/go-pagerduty/pull/108, and the proper fix would probably be to add a `from` argument to the function in `v2.0.0` since it'd be a breaking change.

There was quite a bit of time where the maintenance of this package was best effort by folks without much Go under their belt, and so I suspect this just got missed in the code review due to that lack of context. I've been trying to have more of an eye for these types of details before merging things in.

I'll file a dedicated issue to track this improvement as part of the `v2.0.0.` milestone.

**Comment by theckman** [comment]
@justolinas Tracking this in #337 now. Let me know if there's anything I seem to have missed, and whether you're okay following that issue and closing this one.

**Comment by justolinas** [comment]
@theckman ofcourse, thanks for following up!
