### ISSUE TITLE
Should all fields in Service type be `omitempty

### ISSUE THREAD

**Issue by callumj** [PagerDuty/go-pagerduty#348]
I am trying to just change the `alert_creation` type on a service (via `UpdateService`) and have noticed I cannot just set it as the JSON marshal wants to include `auto_resolve_timeout`, `acknowledgement_timeout`, `escalation_policy` (it isn't a pointer so `omitempty` doesn't work), `support_hours`, `scheduled_actions`. 

Is there a reason a few of these are lacking `omitempty`?

**Comment by theckman** [comment]
@callumj for `EscalationPolicy`, the [API reference documentation](https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1services~1%7Bid%7D/put) indicates it's required when updating a service. So I think that will need to stay as-is.

For the other fields it seems like more of an accidental omission within the package. We should probably fix those with the similar issues we're hoping to address in `v1.5.0`.

**Comment by theckman** [comment]
Change of plans, going to fix this in `v1.4.2` because it broke some things.

**Comment by theckman** [comment]
Slight correction, I'll fix the things that broke in `v1.4.2`. The rest will be done in `v.1.5.0`.

**Comment by theckman** [comment]
@callumj Actually, would you be wiling to raise a PR with `omitempty` added to all fields except `EscalationPolicy`?

Because of how the repo is configured, I can't merge my own PRs without getting a review from a PD employee when they have a spare moment. Those spare cycles can be hard to come by, unfortunately.

I can review and merge the PRs of others, and so if you could raise a PR, and have a moment to address any feedback, it would be a tremendous help in getting this change made.

If not no sweat!
