### ISSUE TITLE
Feature Request: EU Data Location support for Events API

### ISSUE THREAD

**Issue by solita-mikatormanen** [PagerDuty/go-pagerduty#355]
Hi

As Pagerduty extended their support for also EU Data Location, would there be some kind of schedule for the library to support EU endpoints also?

**Comment by theckman** [comment]
Hello,

There isn't a schedule for that, no. I am the primary maintainer of this package, and because I am not a PagerDuty employee I do this on my personal time. This is also the first time I've heard of that feature, it isn't something I would personally use, and there's already substantial amount of work I have queued-up for the upcoming v1.5.0 release.

If you'd be able to raise a PR, and be on-deck to address any feedback, I'd likely be able to make some time to review it and merge when ready.

**Comment by theckman** [comment]
@solita-mikatormanen Actually, it looks like we already implicitly do: 

https://pkg.go.dev/github.com/PagerDuty/go-pagerduty#WithAPIEndpoint
https://pkg.go.dev/github.com/PagerDuty/go-pagerduty#WithV2EventsAPIEndpoint

If you find anything in particular we need to change or implement, could you please open an issue specific to that?
