### ISSUE TITLE
Support Event Transformer Code?

### ISSUE THREAD

**Issue by CannibalVox** [PagerDuty/go-pagerduty#67]
Via a support ticket, I was told earlier today that I can add the code for an event transformer via the config property of the integration payload.  But the integration object in this API doesn't have a config property, so this library cannot be used.

```
{
    "integration": {
        "config": {
            "fields": {
                "code": {
                    "value": "// Hello world"
                }
            }
        },
        "name": "Custom Event Transformer",
        "summary": "My Custom Event Transformer",
        "type": "event_transformer_api_inbound_integration",
        "vendor": {
            "id": "PCJ0EFQ",
            "type": "vendor_reference"
        }
    }
}
```

**Comment by lfepp** [comment]
@CannibalVox the config property of the integration payload is intentionally undocumented as the property is in flux and the endpoint could be updated to support CETs on a different property or through a different endpoint entirely. Since there could be changes to the API that would break this property, I would suggest we avoid adding this to the library until it is a fully documented and supported property.

**Comment by stmcallister** [comment]
Going to close this issue because of its age and inactivity. Please reopen if this issue still exists today.
