### ISSUE TITLE
Swallowing API responses

### ISSUE THREAD

**Issue by bradleyrobinson** [PagerDuty/go-pagerduty#95]
In incident.go, ability.go, addon.go, event.go, and others, the HTTP response is swallowed rather than returned. I don't think it's controversial to suggest that API users might be interested in the API response and they should be the ones deciding whether or not to use the data from the response. 

For example, if someone calls pagerduty.Client.ManageIncidents, they might be interested in seeing how many of their incidents were managed, or get the exact time when they were accepted. Without the response, however, there is no way to do that.

**Comment by theckman** [comment]
@bradleyrobinson we recently merged PRs #265 and #272, which will expose a new `APIError` type that gets returned for API errors. This should address some of your request, although we've chosen not to capture / return the response itself.

For non-error responses, I think it would be better to ensure our structures are able to deserialize the JSON so that we can provide that back to consumers. I'm not confident that the majority of API calls should be returning the full response, since I would expect 90%+ of users would not consume that.

A compromise might be to expose `pagerduty.Client.Do()` method that allows you to make request against the PagerDuty API, so that you can inspect the raw response if you wish to.

What are your thoughts on this, considering I'm looking at this over 3 years later. 😅

**Comment by theckman** [comment]
With #325 being merged in, to be included in v1.5.0 when it's ready, I think we've effectively solved this feature request. While it does take some extra coordination on the consumer to capture the responses safely, it can now be implemented for all API calls to PagerDuty. Feel free to raise another issue if #325 doesn't give you the ability you want/need.
